### Create a new user (SignUp)
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "jose2@thebest.com",
    "password": "5234523rgds"
}

### Signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "jose2@thebest.com",
    "password": "5234523rgds"
}

### signOut
POST http://localhost:3000/auth/signout

### Return a user with current user decorator
GET http://localhost:3000/auth/whoami

### Find a user with id
GET http://localhost:3000/auth/2

### Find All users with specific IsEmail
GET http://localhost:3000/auth?email=jose@thebest.com

### Remove user with id
DELETE http://localhost:3000/auth/1

### Update user with id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "jose@update.com"
}